// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pizzaria;

#nullable disable

namespace API_Estacionamento.Migrations
{
    [DbContext(typeof(PizzariaDBContext))]
    [Migration("20230919000644_CleintePedido")]
    partial class CleintePedido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("pizzaria.Cliente", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Cpf");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("pizzaria.PedidoFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteCpf")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCpf");

                    b.ToTable("PedidoFinal");
                });

            modelBuilder.Entity("pizzaria.PedidoFinal", b =>
                {
                    b.HasOne("pizzaria.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCpf");

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
