// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pizzaria;

#nullable disable

namespace API_Estacionamento.Migrations
{
    [DbContext(typeof(PizzariaDBContext))]
    [Migration("20230920140018_GetterSetters")]
    partial class GetterSetters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("pizzaria.Cliente", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Cpf");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("pizzaria.PedidoFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteCpf")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCpf");

                    b.ToTable("PedidoFinal");
                });

            modelBuilder.Entity("pizzaria.PizzaPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PedidoFinalId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.Property<string>("TamanhoNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PedidoFinalId");

                    b.HasIndex("TamanhoNome");

                    b.ToTable("PizzaPedido");
                });

            modelBuilder.Entity("pizzaria.Sabor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PizzaPedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PizzaPedidoId");

                    b.ToTable("Sabor");
                });

            modelBuilder.Entity("pizzaria.Tamanho", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<double>("MultiplicadorPreco")
                        .HasColumnType("REAL");

                    b.Property<int>("QntdFatias")
                        .HasColumnType("INTEGER");

                    b.HasKey("Nome");

                    b.ToTable("Tamanho");
                });

            modelBuilder.Entity("pizzaria.PedidoFinal", b =>
                {
                    b.HasOne("pizzaria.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCpf");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("pizzaria.PizzaPedido", b =>
                {
                    b.HasOne("pizzaria.PedidoFinal", null)
                        .WithMany("Pizzas")
                        .HasForeignKey("PedidoFinalId");

                    b.HasOne("pizzaria.Tamanho", "Tamanho")
                        .WithMany()
                        .HasForeignKey("TamanhoNome")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tamanho");
                });

            modelBuilder.Entity("pizzaria.Sabor", b =>
                {
                    b.HasOne("pizzaria.PizzaPedido", null)
                        .WithMany("Sabores")
                        .HasForeignKey("PizzaPedidoId");
                });

            modelBuilder.Entity("pizzaria.PedidoFinal", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("pizzaria.PizzaPedido", b =>
                {
                    b.Navigation("Sabores");
                });
#pragma warning restore 612, 618
        }
    }
}
